//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cfg_Corp_Category
    {
        public int corp_category_id { get; set; }
        public int catId { get; set; }
        public int parentId { get; set; }
        public string name { get; set; }
        public int catClass { get; set; }
        public string category_detail { get; set; }
        public int corp_id { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modified_time { get; set; }
        public int is_delete { get; set; }
    }
}
