//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Employee_Welfare_DBEntities : DbContext
    {
        public Employee_Welfare_DBEntities()
            : base("name=Employee_Welfare_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cfg_Corp_Category> Cfg_Corp_Category { get; set; }
        public virtual DbSet<Cfg_Corp_Phone_Message_Header> Cfg_Corp_Phone_Message_Header { get; set; }
        public virtual DbSet<Cfg_Corp_Sale> Cfg_Corp_Sale { get; set; }
        public virtual DbSet<Shopping_Area> Shopping_Area { get; set; }
        public virtual DbSet<Shopping_Category> Shopping_Category { get; set; }
        public virtual DbSet<Shopping_Customer_Address> Shopping_Customer_Address { get; set; }
        public virtual DbSet<Shopping_Token> Shopping_Token { get; set; }
        public virtual DbSet<Welfare_Corporation> Welfare_Corporation { get; set; }
        public virtual DbSet<Welfare_Corporation_Point_Log> Welfare_Corporation_Point_Log { get; set; }
        public virtual DbSet<Welfare_Customer_Point_Log> Welfare_Customer_Point_Log { get; set; }
        public virtual DbSet<Welfare_Customer_Token> Welfare_Customer_Token { get; set; }
        public virtual DbSet<Welfare_Department> Welfare_Department { get; set; }
        public virtual DbSet<Welfare_Mobile_Phone_Message> Welfare_Mobile_Phone_Message { get; set; }
        public virtual DbSet<Welfare_System_Bug_Log> Welfare_System_Bug_Log { get; set; }
        public virtual DbSet<Shopping_JD_Order_Log> Shopping_JD_Order_Log { get; set; }
        public virtual DbSet<Shopping_Order_Detail> Shopping_Order_Detail { get; set; }
        public virtual DbSet<Shopping_Order_Master> Shopping_Order_Master { get; set; }
        public virtual DbSet<Cfg_Corp_ConfirmOrder> Cfg_Corp_ConfirmOrder { get; set; }
        public virtual DbSet<Cfg_Shopping_HomePage_Category> Cfg_Shopping_HomePage_Category { get; set; }
        public virtual DbSet<Cfg_Shopping_HomePage_Img> Cfg_Shopping_HomePage_Img { get; set; }
        public virtual DbSet<Shopping_Product_Info> Shopping_Product_Info { get; set; }
        public virtual DbSet<Cfg_Notice_Customer> Cfg_Notice_Customer { get; set; }
        public virtual DbSet<Welfare_Enum> Welfare_Enum { get; set; }
        public virtual DbSet<Welfare_Notice> Welfare_Notice { get; set; }
        public virtual DbSet<Cfg_Welfare_Customer> Cfg_Welfare_Customer { get; set; }
        public virtual DbSet<Welfare_Customer_Login_Log> Welfare_Customer_Login_Log { get; set; }
        public virtual DbSet<Welfare_Customer> Welfare_Customer { get; set; }
        public virtual DbSet<Shopping_Cart> Shopping_Cart { get; set; }
    }
}
