//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Order_Detail
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public string goods_name { get; set; }
        public long skuId { get; set; }
        public int num { get; set; }
        public decimal goods_pt_price { get; set; }
        public decimal goods_jd_price { get; set; }
        public decimal tax { get; set; }
        public int oid { get; set; }
        public int goods_type { get; set; }
        public decimal splitFreight { get; set; }
        public decimal taxPrice { get; set; }
        public decimal nakedPrice { get; set; }
        public long jd_OrderId { get; set; }
        public int is_delete { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modified_time { get; set; }
        public string img_path { get; set; }
        public int cid_1 { get; set; }
        public int cid_2 { get; set; }
        public int cid_3 { get; set; }
        public string cid_1_name { get; set; }
        public string cid_2_name { get; set; }
        public string cid_3_name { get; set; }
    }
}
