//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Cart
    {
        public int cart_id { get; set; }
        public int customer_id { get; set; }
        public int product_id { get; set; }
        public long skuid { get; set; }
        public int product_num { get; set; }
        public string product_name { get; set; }
        public string product_img { get; set; }
        public decimal product_jdprice { get; set; }
        public decimal product_ptprice { get; set; }
        public System.DateTime modified_time { get; set; }
        public int is_delete { get; set; }
        public System.DateTime create_time { get; set; }
        public decimal sale_value { get; set; }
        public decimal product_price { get; set; }
    }
}
