//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Token
    {
        public int id { get; set; }
        public string token_type_name { get; set; }
        public string access_token { get; set; }
        public string refresh_token { get; set; }
        public long update_time_stamp { get; set; }
        public int expires_in { get; set; }
        public long refresh_token_expires { get; set; }
        public System.DateTime create_time { get; set; }
        public int is_delete { get; set; }
        public System.DateTime modified_time { get; set; }
    }
}
