//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Order_Master
    {
        public int order_id { get; set; }
        public long order_sn { get; set; }
        public int customer_id { get; set; }
        public string shopping_user_name { get; set; }
        public string shopping_phone { get; set; }
        public string province_name { get; set; }
        public string city_name { get; set; }
        public string county_name { get; set; }
        public string town_name { get; set; }
        public string user_address { get; set; }
        public int payment_method { get; set; }
        public decimal order_pt_money { get; set; }
        public decimal order_jd_money { get; set; }
        public decimal freight { get; set; }
        public int jd_order_state { get; set; }
        public int is_pay { get; set; }
        public Nullable<System.DateTime> pay_time { get; set; }
        public decimal orderNakedPrice { get; set; }
        public decimal orderTaxPrice { get; set; }
        public int is_order_split { get; set; }
        public int logistics_state { get; set; }
        public System.DateTime modified_time { get; set; }
        public System.DateTime create_time { get; set; }
        public decimal corp_sale { get; set; }
        public string thirdOrder { get; set; }
        public int is_delete { get; set; }
    }
}
