//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Welfare_Corporation
    {
        public int corp_id { get; set; }
        public string corp_name { get; set; }
        public string corp_sname { get; set; }
        public string corp_people_name { get; set; }
        public int corp_people_gender { get; set; }
        public string corp_people_phone { get; set; }
        public string corp_email { get; set; }
        public string corp_number { get; set; }
        public string logo_path { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public System.DateTime modified_time { get; set; }
        public int is_delete { get; set; }
    }
}
