//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Welfare_Customer
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string login_name { get; set; }
        public string login_password { get; set; }
        public int customer_state { get; set; }
        public int corp_id { get; set; }
        public int department_id { get; set; }
        public int identity_card_type { get; set; }
        public string identity_card_no { get; set; }
        public string mobile_phone { get; set; }
        public string customer_email { get; set; }
        public int gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<System.DateTime> entry_time { get; set; }
        public decimal user_money { get; set; }
        public decimal user_point { get; set; }
        public int is_test_customer { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modified_time { get; set; }
        public int is_delete { get; set; }
        public string head_img { get; set; }
    }
}
